# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_imagine:
    resource: .
    type:     imagine

#=============== Without Locale ==============
_login_check:
    pattern: /login_check

_login:
    pattern: /login
    defaults: { _controller: SurgePeerPlatformBundle:Login:login }

_logout:
  pattern: /logout

#=============== With Locale ==================

_familytree_bundle:
    resource: "@SurgePeerPlatformBundle/Controller"
    type: annotation
