services:
    twig.extension.text:
         class: Twig_Extensions_Extension_Text
         tags:
             - { name: twig.extension }
    ftree.login_listener:
         class: FTree\FamilyTreeBundle\EventListener\LoginListener
         arguments:
             - "@router"
             - "@security.context"
             - "@event_dispatcher"
             - "@session"
             - "@service_container"
         tags:
             - {name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin}

    ftree.type.htmlawed_field:
         class: FTree\FamilyTreeBundle\Form\Type\HtmlawedFieldType
         arguments: ["@service_container", 'xss_filter', 'textarea']
         tags:
             - { name: form.type, alias: htmlawed_textarea }

    ftree.cron_helper:
        class: FTree\FamilyTreeBundle\Service\CronHelper
        arguments: ["%kernel.root_dir%/cache/"]

    ftree_familytree.main_repo:
        class: FTree\FamilyTreeBundle\Repository\MainRepository
        arguments:
            - "@doctrine.orm.default_entity_manager"

    ftree_familytree.mailer:
        class: FTree\FamilyTreeBundle\Mailer\Mailer
        arguments:
            - "@mailer"
            - "@router"
            - "@twig"
            - "@service_container"

    ftree.exception_listener:
        class: FTree\FamilyTreeBundle\EventListener\ExceptionListener
        arguments:
            - "@logger"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException , priority: -1}
            - { name: monolog.logger, channel: exception_logger }

    ftree.twig.extension:
        class: FTree\FamilyTreeBundle\Twig\FTreeExtension
        arguments:
            - "@service_container"
        tags:
            - { name: twig.extension }

    ftree.entity_lifecycle_events_listener:
        class: FTree\FamilyTreeBundle\EventListener\EntityLifecycleEventsListener
        arguments:
            - "@service_container"
            - %uploadRoot%
        tags:
            - { name: doctrine.event_listener, event: prePersist}
            - { name: doctrine.event_listener, event: postPersist}
            - { name: doctrine.event_listener, event: preUpdate}
            - { name: doctrine.event_listener, event: postUpdate}
            - { name: doctrine.event_listener, event: postRemove }